### ISSUE TITLE
Error when installing from source v 1.5.0

### ISSUE THREAD

**Issue by nocturnalguru** [MartijnOud/SERP-counter#11]
![image](https://user-images.githubusercontent.com/18275383/148823323-b6ef1392-7a74-4ca3-9ea0-24addfce3cce.png)

Admittedly, I do not generally install from source very often, but I am getting this error.

Running on ubuntu 20.04 LTS

I extracted the files inside the default user directory (in my case is 'Profile 1') and then using the chrome://extensions gui I activated it.

am I missing something or is this an error?

**Comment by nocturnalguru** [comment]
PS.  Love the extension!

**Comment by MartijnOud** [comment]
Hey, thanks for letting me know! No you're not missing anything, this looks like a bug. I'm not immediately able to reproduce it so I'll look into it and report back.

**Comment by MartijnOud** [comment]
I think it should be resolved now! I can't be 100% sure because I'm not seeing this error but the commit should address it.

If it's easier, you can also test the extension by copying everything in `serpcounter.js` and pasting it in your console in an incognito window. There won't be CSS styling but you'll either see the numbers or another syntax error.

**Comment by nocturnalguru** [comment]
It's looks like it is working!  Thank you!
